### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by bthibault** [agmoyano/modelling#1]
npm ERR! Error: No compatible version found: waterline@'balderdashy/waterline'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.0.1","0.0.2","0.0.4","0.0.5","0.0.51","0.0.52","0.0.5201","0.0.5202","0.0.5204","0.0.5205","0.0.6","0.0.7","0.1.0","0.1.5","0.1.5-1","0.1.6-0","0.2.0","0.3.0","0.4.0","0.4.1","0.4.2","0.4.4","0.4.5","0.4.6","0.4.7","0.5.0","0.5.1","0.5.2","0.6.0","0.6.1","0.9.0","0.9.1","0.9.2","0.9.3","0.9.4","0.9.5","0.9.6","0.9.7","0.9.8","0.9.9","0.9.10","0.9.11","0.10.0-rc1","0.10.0-rc2","0.10.0-rc3","0.9.12","0.9.13","0.10.0-rc4","0.9.14","0.10.0-rc5","0.9.15","0.10.0-rc6","0.9.16","0.10.0-rc7","0.10.0-rc8","0.10.0-rc9","0.10.0-rc10","0.10.0-rc11","0.10.0-rc12","0.10.0-rc13","0.10.0-rc14","0.10.0-rc15","0.10.1","0.10.2","0.10.3","0.10.4","0.10.5","0.10.6","0.10.7","0.10.8","0.10.9","0.10.10","0.10.11","0.10.12","0.10.13","0.10.14","0.10.15","0.10.16","0.10.17","0.10.18","0.10.19","0.10.20","0.10.21","0.10.22-rc1","0.10.22","0.10.23","0.1.1","0.1.3","0.1.4"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-53-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "modelling"
npm ERR! cwd /var/www-services/OpenIDConnect/examples
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www-services/OpenIDConnect/examples/npm-debug.log
npm ERR! not ok code 0

**Comment by agmoyano** [comment]
Hi, sorry it took so long, but now it should be fixed.

Cheers
